events {
    worker_connections 1024;
}

http {
    server {
        # Listen on port 80 for internal domain or IP access
        listen 80;
        
        #server_name = placeholder
        server_name localhost;

        # Frontend Route
        location / {
            # Tentuin frontend stack dulu, proxy_pass masih placeholder
            # kalo udah fix (e.g. Node) jalan di port 3000, uncomment proxy_pass
            # proxy_pass http://frontend:3000;
            
            # Temporary response buat testing
            default_type text/html;
            return 200 '<html><body><h1>Cesium Platform: Frontend Service</h1></body></html>';
        }

        # Backend API Route
        location /api/ {
            # Sama masih placeholder
            # proxy_pass http://backend:8080/;
            
            default_type application/json;
            return 200 '{"status":"success","message":"Cesium Platform: Backend API"}';
        }
    }
}
